default_format: csv

csv:
  format: csv
  reader_options:
    header: true
    inferSchema: true
    delimiter: ","

excel:
  format: excel
  reader_options:
    header: true
    inferSchema: true
    # dataAddress: "'Sheet1'!A1"
    treatEmptyValuesAsNulls: true
  columns_type: {}

parquet:
  format: parquet
  reader_options:
    inferSchema: true
  columns_type: {}
