extractor_config:
  source_directories:
    # - "../../Spark/data/"
    - "../../file_reader/"
    - "../data/"

  files_extensions:
    - ".csv"
    # - '.json'
    - ".parquet"
    - ".xlsx"
  include_files:
    - "*IMDB*"
    - "*creditcard*"
    - "*person*"
    # - "**"
    - "orders_*"
  exclude_files:
    - "file1_*.csv"
    - "*file2_*.csv"
